default_language_version:
  python: python
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: make-requirements
        name: "Make requirements.txt"
        entry: make
        language: system
        args: [ "requirements.txt" ]
  - repo: local
    hooks:
      - id: sync-ruff-version
        name: "Set ruff version in pyproject.toml to .pre-commit-config.yaml"
        entry: make
        language: system
        args: [ "sync-ruff-version" ]
        pass_filenames: false
