[project]
name = "metropolis"
version = "2.3"
description = "William Lyon Mackenzie's online hub for announcements, calendar events, clubs, and timetables"
readme = "README.md"
license = "AGPL-3.0-or-later"
authors = [
    { name = "nyiyui", email = "+@nyiyui.ca"},
    { name = "Jason Cameron", email = "jason@jasoncameron.dev"},
]
dynamic = ["dependencies", "requires-python"]

[project.urls]
homepage = "https://maclyonsden.com/"
repository = "https://github.com/wlmac/metropolis"
documentation = "https://docs.maclyonsden.com"

[tool.poetry.dependencies]
python = "~3.12"
asgiref = "^3.7.2"
bleach = "~4"
certifi = "*"
cffi = "*"
charset-normalizer = "*"
cryptography = "^46.0.7"
defusedxml = "^0.7.1"
Django = "^5.1.15"
django-allauth = "~65.14"
django-cors-headers = "^3.10.0"
django-oauth-toolkit = "^3.0.1"
django-pwa = "*"
django-redis = "^5.0.0"
django-select2 = "*"
djangorestframework = "*"
djangorestframework-simplejwt = "*"
Markdown = ">3.0.0"
martor = "*"
oauthlib = "^3.2.2"
pillow = "^12.1.1"
pytz = "*"
redis = "^4.4.4"
requests = "*"
requests-oauthlib = "*"
urllib3 = "*"
django_ical = "~1.8"
celery = "*"
exponent_server_sdk = "*"
django-hijack = "*"
drf-spectacular = "0.27.0"
memoization = "^0.4.0"
psycopg = [
    { version = "~3.1", markers = "sys_platform == 'linux'" },
    { extras = [
        "binary",
    ], version = "~3.1", markers = "sys_platform != 'linux'" },
]
gunicorn = "^23.0.0"
sentry-sdk = { extras = ["django", "celery"], version = "^2.8.0" }
gspread = "^6.1.4"
google-genai = "^1.0.0"
django-reversion = "^5.1.0"

[tool.poetry.group.dev.dependencies]
django-stubs = "*"
pre-commit = "^4.5.1"
ruff = "0.15.10"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.ruff]
exclude = ["core/migrations", ".gitignore"]

[tool.ruff.lint]
select = [ # https://docs.astral.sh/ruff/rules/
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM",
    "C4",
    # "FIX",
]
ignore = ["E501", "C408"]

[tool.ruff.format]
docstring-code-format = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "metropolis.settings"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
