# Generated by Django 3.2.6 on 2021-08-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210814_2310"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="approver",
            new_name="supervisor",
        ),
    ]
