# Generated by Django 3.2.6 on 2021-08-15 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_approver_announcement_supervisor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="authors",
        ),
        migrations.AddField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
