# Generated by Django 3.2.6 on 2021-08-15 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20210815_0117"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.AddField(
            model_name="announcement",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                help_text="This older announcement will be replaced by the announcement being edited right now.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.announcement",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Whether if this announcement pertains to the general school population, not just those in the organization.",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                help_text="Only fill this field in if you are rejecting this announcement.",
                max_length=140,
                verbose_name="reason for rejection",
            ),
        ),
    ]
