# Generated by Django 3.2.6 on 2021-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20210822_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
