# Generated by Django 3.2.6 on 2021-08-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_organization_applications_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="banner",
            field=models.ImageField(blank=True, upload_to="banners"),
        ),
        migrations.AddField(
            model_name="organization",
            name="icon",
            field=models.ImageField(blank=True, upload_to="icons"),
        ),
    ]
