# Generated by Django 3.2.6 on 2021-08-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_organizationurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="color",
        ),
    ]
