# Generated by Django 3.2.6 on 2021-08-30 09:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, null=True),
        ),
    ]
