# Generated by Django 3.2.6 on 2021-08-30 09:26

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    for row in Organization.objects.all():
        row.slug = uuid.uuid4()
        row.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_organization_slug"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
