# Generated by Django 3.2.6 on 2021-08-30 09:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20210830_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
