# Generated by Django 3.2.6 on 2021-08-31 02:16

from django.db import migrations, models

import core.models.organization


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20210830_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="banner",
            field=models.ImageField(
                default="banners/default.png",
                upload_to=core.models.organization.banner_file_path_generator,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="icon",
            field=models.ImageField(
                default="icons/default.png",
                upload_to=core.models.organization.icon_file_path_generator,
            ),
        ),
    ]
