# Generated by Django 3.2.6 on 2021-08-31 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models.post


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_event_is_instructional"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=128)),
                ("body", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "featured_image",
                    models.ImageField(
                        default="featured_image/default.png",
                        upload_to=core.models.post.featured_image_file_path_generator,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogposts_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blogposts",
                        related_query_name="blogpost",
                        to="core.Tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_modified_date"],
                "abstract": False,
            },
        ),
    ]
