# Generated by Django 3.2.6 on 2021-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default="default", unique=True),
            preserve_default=False,
        ),
    ]
