# Generated by Django 3.2.6 on 2021-09-01 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_event_schedule_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Whether if this event pertains to the general school population, not just those in the organization.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                related_query_name="event",
                to="core.organization",
            ),
            preserve_default=False,
        ),
    ]
