# Generated by Django 3.2.6 on 2021-09-01 10:59

from django.db import migrations, models

import core.models.organization


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_event_schedule_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="banner",
            field=models.ImageField(
                blank=True,
                default="banners/default.png",
                upload_to=core.models.organization.banner_file_path_generator,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="icons/default.png",
                upload_to=core.models.organization.icon_file_path_generator,
            ),
        ),
    ]
