# Generated by Django 3.2.6 on 2021-09-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-created_date"]},
        ),
    ]
