# Generated by Django 3.2.6 on 2021-09-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_blogpost_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "club"},
        ),
    ]
