# Generated by Django 3.2.6 on 2021-09-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_organization_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="description",
            new_name="long_description",
        ),
    ]
