# Generated by Django 3.2.6 on 2021-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_rename_description_organization_long_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
