# Generated by Django 3.2.6 on 2021-09-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_rename_description_organization_long_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
