# Generated by Django 3.2.6 on 2021-09-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_auto_20210913_0226"),
        ("core", "0036_user_is_teacher"),
    ]

    operations = []
