# Generated by Django 3.2.6 on 2021-09-14 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_merge_0036_auto_20210913_0226_0036_user_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
