# Generated by Django 3.2.6 on 2021-09-14 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_user_graduating_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations_supervising",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
