# Generated by Django 3.2.6 on 2021-10-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_tag_name"),
        ("core", "0045_auto_20211007_2353"),
    ]

    operations = []
