# Generated by Django 3.2.15 on 2022-09-22 16:19

from django.db import migrations, models
from django.db.models import F


def migrate_show_after_announcement(apps, schema_editor):
    Announcement = apps.get_model("core","Announcement")
    Announcement.objects.all().update(show_after=F('created_date'))

def migrate_show_after_blogpost(apps, schema_editor):
    BlogPost = apps.get_model("core","BlogPost")
    BlogPost.objects.all().update(show_after=F('created_date'))

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20220308_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-show_after']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_after',
            field=models.DateTimeField(default="2022-09-22T16:23Z"),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_show_after_announcement,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_after',
            field=models.DateTimeField(default="2022-09-22T16:23Z"),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_show_after_blogpost,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Pending Approval'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_instructional',
            field=models.BooleanField(default=True, help_text='Whather school instruction is taking place during this event. Leave checked if not direct cause.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduating_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Does not apply'), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], null=True),
        ),
    ]
