# Generated by Django 3.2.10 on 2022-01-20 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20211207_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Only fill this field in if you are rejecting this announcement.', max_length=140, verbose_name='reason for rejection'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('p', 'Pending Approval'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogposts_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
