# Generated by Django 3.2.15 on 2022-09-27 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_auto_20220922_1619"),
        ("core", "0051_auto_20220926_2257"),
    ]

    operations = []
