# Generated by Django 3.2.10 on 2022-03-10 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_rfp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfp',
            options={'ordering': ['-created_date'], 'verbose_name': 'RfP'},
        ),
    ]
