# Generated by Django 3.2.10 on 2022-02-02 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0051_auto_20220120_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PubReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('p', 'Pending Approval'), ('a', 'Approved'), ('r', 'Rejected')], max_length=1)),
                ('rej_why', models.CharField(blank=True, help_text='Only fill this field in if you are rejecting this request.', max_length=140, verbose_name='reason for rejection')),
                ('approvers', models.ManyToManyField(related_name='pubreqs_to_approve', to=settings.AUTH_USER_MODEL)),
                ('requesters', models.ManyToManyField(related_name='supporting_pubreqs', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
