# Generated by Django 3.2.10 on 2022-03-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_rfp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='Only fill this field in if you are rejecting this announcement.', max_length=140, verbose_name='reason for rejection'),
        ),
    ]
