# Generated by Django 3.2.17 on 2023-02-14 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0058_fix_blogpost_featured_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_announcements',
            field=models.ManyToManyField(blank=True, to='core.Announcement'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_blogs',
            field=models.ManyToManyField(blank=True, to='core.BlogPost'),
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField(max_length=512)),
                ('live', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('likes', models.ManyToManyField(blank=True, to='core.Like')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
                ('saves', models.ManyToManyField(blank=True, to='core.Save')),
                ('user', models.ForeignKey(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.Comment'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.Like'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='saves',
            field=models.ManyToManyField(blank=True, to='core.Save'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.Comment'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.Like'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='saves',
            field=models.ManyToManyField(blank=True, to='core.Save'),
        ),
    ]
