# Generated by Django 3.2.15 on 2023-02-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20230217_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'permissions': (('view_nodelay', 'View without delay'),)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='subject_type',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='save',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='live',
            field=models.BooleanField(default=True, help_text='Shown publicly?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='saves',
            field=models.ManyToManyField(blank=True, help_text='The users who saved this comment', to='core.Save'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['subject_type', 'subject_id'], name='core_commen_subject_0fd540_idx'),
        ),
    ]
