# Generated by Django 4.0.10 on 2023-04-11 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_remove_recurrencerule_ends_after_greater_than_starts_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recurrencerule",
            name="ends_or_ends_after",
        ),
    ]
