# Generated by Django 4.0.10 on 2023-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_announcement_author_alter_announcement_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='The users who liked this comment', to='core.like'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='The users who liked this comment', to='core.like'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
