# Generated by Django 4.0.10 on 2023-03-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_announcement_likes_alter_blogpost_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='history',
            field=models.ManyToManyField(blank=True, to='core.commenthistory'),
        ),
    ]
