# Generated by Django 4.0.10 on 2023-04-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_recurrencerule_ends_or_ends_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencerule',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reoccurrences', related_query_name='reoccurrence', to='core.event'),
        ),
    ]
