# Generated by Django 4.0.10 on 2023-04-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_exhibit'),
        ('core', '0063_alter_recurrencerule_event'),
    ]

    operations = [
    ]
