# Generated by Django 4.0.10 on 2023-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_announcement_likes_remove_blogpost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_notif_token',
            field=models.TextField(blank=True, null=True, verbose_name='Expo Notifications Token'),
        ),
    ]
