# Generated by Django 4.0.10 on 2023-06-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_merge_0062_exhibit_0063_alter_recurrencerule_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduating_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Does not apply'), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True),
        ),
    ]
