# Generated by Django 4.0.10 on 2023-09-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_user_graduating_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived posts are not shown on the blog page.'),
        ),
        migrations.AlterField(
            model_name='recurrencerule',
            name='type',
            field=models.IntegerField(choices=[(3, 'Daily'), (2, 'Weekly'), (1, 'Monthly'), (0, 'Yearly')], help_text='the type of repetition. (e.g. daily, weekly, monthly, yearly)'),
        ),
    ]
