# Generated by Django 4.1.10 on 2023-09-22 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_auto_20230221_1937_squashed_0065_user_expo_notif_token"),
        ("core", "0066_blogpost_is_archived_alter_recurrencerule_type"),
    ]

    operations = []
