# Generated by Django 4.1.10 on 2023-09-22 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_merge_20230921_2017"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecurrenceRule",
        ),
    ]
