# Generated by Django 4.1.13 on 2024-01-02 18:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text


def populate_bios(apps, schema_editor):
	global row
	User = apps.get_model("core", "User")
	for pk, bio in settings.METROPOLIS_STAFF_BIO.items():
		try:
			row = User.objects.get(pk=pk)
		except User.DoesNotExist:
			print(f"User {pk} does not exist")
		row.staff_bio = bio
		row.save(update_fields=["staff_bio"])

def undo_populate_bios(apps, schema_editor):
	raise NotImplementedError("Please only revert this once you have backed up all bios. This is irreversible.")
	# replace the above line with pass if you want to revert this migration

class Migration(migrations.Migration):
	dependencies = [
		(
			"core",
			"0058_fix_blogpost_featured_image_description_squashed_0068_remove_user_expo_notif_token_delete_recurrencerule",
		),
	]
	
	operations = [
		migrations.AlterModelOptions(
			name="user",
			options={},
		),
		migrations.AddField(
			model_name="user",
			name="staff_bio",
			field=models.TextField(
				blank=True, help_text="Staff bio for Metropolis staff", null=True
			),
		),
		migrations.RunPython(populate_bios, reverse_code=undo_populate_bios),
		
		migrations.AddConstraint(
			model_name="user",
			constraint=models.UniqueConstraint(
				django.db.models.functions.text.Lower("username"),
				name="username-lower-check",
			),
		),
	]
