# Generated by Django 5.0 on 2024-02-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_user_deleted_at_user_is_deleted_alter_comment_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="timezone",
        ),
    ]
