# Generated by Django 5.1.5 on 2025-01-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_dailyannouncement_alter_event_is_instructional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gcal_id',
            field=models.CharField(default=None, editable=False, help_text='Unique identifier for events that are automatically created using data from the official WLMAC calendar. Should not be manually edited.', max_length=1024, null=True, unique=True),
        ),
    ]
