# Generated by Django 5.1.10 on 2025-09-02 21:43

import core.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_event_gcal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='years',
            field=core.utils.fields.ChoiceArrayField(base_field=models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')]), help_text='The years the user was a staff member. Used to determine if the user is an alumni.', size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduating_year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Does not apply'), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], null=True),
        ),
    ]
