# Generated by Django 5.1.10 on 2025-09-22 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_staffmember_years_alter_user_graduating_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='owners',
            field=models.ManyToManyField(related_name='organizations_owning', to=settings.AUTH_USER_MODEL),
        ),
    ]
