# Generated by Django 5.1.10 on 2025-10-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_organization_owner_organization_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='applications_open',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='show_members',
        ),
    ]
