# Generated by Django 5.1.10 on 2025-10-13 21:07

import core.models.timetable
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_organization_applications_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='courses_str',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='timetable',
            name='title',
            field=models.CharField(default='New timetable', max_length=64),
        ),
    ]
