# Generated by Django 5.1.13 on 2025-10-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_timetable_courses_str_timetable_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
