# Generated by Django 5.1.13 on 2025-11-02 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization_string',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', related_query_name='announcement', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', False), ('organization_string__isnull', False), _connector='OR'), name='organization_or_organization_string_required'),
        ),
    ]
