# Generated by Django 5.1.14 on 2025-11-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Give the banner a name! Only used for admin purposes to differentiate banners, not displayed elsewhere', max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('icon_url', models.CharField(blank=True, max_length=150)),
                ('cta_link', models.CharField(blank=True, max_length=150)),
                ('cta_label', models.CharField(blank=True, help_text='Required only if cta_link is present', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cta_link', ''), models.Q(models.Q(('cta_link', ''), _negated=True), models.Q(('cta_label', ''), _negated=True)), _connector='OR'), name='cta_label_requirement'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_to_start_date')],
            },
        ),
    ]
