# Generated by Django 5.1.15 on 2026-02-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_announcement_author_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('p1_start', models.TimeField()),
                ('p1_end', models.TimeField()),
                ('p2_start', models.TimeField()),
                ('p2_end', models.TimeField()),
                ('p3_start', models.TimeField()),
                ('p3_end', models.TimeField()),
                ('p4_start', models.TimeField()),
                ('p4_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedulepattern')),
            ],
        ),
    ]
