# Generated by Django 5.1.15 on 2026-02-22 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_schedulepattern_scheduleoverride'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_timetable_owner_and_term',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='term',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to=settings.AUTH_USER_MODEL),
        ),
    ]
