# Generated by Django 5.1.15 on 2026-02-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_timetable_unique_timetable_owner_and_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='event',
            name='term',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
