# Generated by Django 5.1.15 on 2026-03-01 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_remove_timetable_courses_remove_event_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='courses_str',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(default='My timetable', max_length=64),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name', models.CharField(blank=True, max_length=32)),
                ('room', models.CharField(blank=True, max_length=16)),
                ('teacher', models.CharField(blank=True, max_length=32)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.timetable')),
            ],
            options={
                'ordering': ['period'],
                'constraints': [models.UniqueConstraint(fields=('timetable', 'period'), name='unique_period_per_timetable_course')],
            },
        ),
    ]
