# Generated by Django 5.1.15 on 2026-03-01 22:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_timetable_courses_str_alter_timetable_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleoverride',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='schedulepattern',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_pattern_name'),
        ),
        migrations.AddConstraint(
            model_name='schedulepattern',
            constraint=models.CheckConstraint(condition=models.Q(('p1_start__lte', models.F('p1_end')), ('p1_end__lte', models.F('p2_start')), ('p2_start__lte', models.F('p2_end')), ('p2_end__lte', models.F('p3_start')), ('p3_start__lte', models.F('p3_end')), ('p3_end__lte', models.F('p4_start')), ('p4_start__lte', models.F('p4_end'))), name='period_times_in_order'),
        ),
    ]
