# Generated by Django 5.2.13 on 2026-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_scheduleoverride_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAnnouncement',
        ),
        migrations.DeleteModel(
            name='Raffle',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentHistory',
        ),
    ]
