# Generated by Django 5.2.13 on 2026-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_comment_author_remove_comment_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tags_following',
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='followers', related_query_name='follower', to='core.organization'),
        ),
    ]
