# Generated by Django 3.1.3 on 2021-02-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20201123_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_frozen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='courses',
            field=models.ManyToManyField(related_name='timetables', to='timetable.Course'),
        ),
    ]
